# Feature extraction

In [2]:
import pandas as pd
import numpy as np
import pickle

In [3]:
df = pickle.load(open('dataset_output.pkl','rb'))

In [4]:
df.head(2)

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,1,Australia,Sri Lanka,0.1,0,0,NaN,Melbourne Cricket Ground
1,1,Australia,Sri Lanka,0.2,0,0,NaN,Melbourne Cricket Ground

# Featute Needed
batting_team , 
bowling_team, city , current_score, ball_left , wickets_left,current rr,last five

In [5]:
df.isnull().sum()

match_id               0
batting_team           0
bowling_team           0
ball                   0
runs                   0
player_dismissed       0
city                8671
venue                  0
dtype: int64

In [6]:
df[df['city'].isnull()]['venue'].value_counts()

venue
Dubai International Cricket Stadium        3092
Pallekele International Cricket Stadium    2066
Melbourne Cricket Ground                   1453
Sydney Cricket Ground                       749
Adelaide Oval                               498
Harare Sports Club                          372
Sharjah Cricket Stadium                     249
Sylhet International Cricket Stadium        128
Carrara Oval                                 64
Name: count, dtype: int64

In [7]:
df['city'] = np.where(
df['city'].isnull() ,
df['venue'].str.split().apply(lambda x:x[0]),
df['city']
 )

In [8]:
df.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [9]:
df.drop(columns = ['venue']  , axis = 1)

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,1,Australia,Sri Lanka,0.1,0,0,Melbourne
1,1,Australia,Sri Lanka,0.2,0,0,Melbourne
2,1,Australia,Sri Lanka,0.3,1,0,Melbourne
3,1,Australia,Sri Lanka,0.4,2,0,Melbourne
4,1,Australia,Sri Lanka,0.5,0,0,Melbourne
...,...,...,...,...,...,...,...
116542,963,Sri Lanka,Australia,19.3,1,0,Colombo
116543,963,Sri Lanka,Australia,19.4,0,0,Colombo
116544,963,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
116545,963,Sri Lanka,Australia,19.6,2,0,Colombo
116546,963,Sri Lanka,Australia,19.7,1,0,Colombo

In [49]:
eligible_city = df['city'].value_counts()[df['city'].value_counts() > 600].index.tolist()
df = df[df['city'].isin(eligible_city)]
eligible_city

['Colombo',
 'Mirpur',
 'Johannesburg',
 'Dubai',
 'Auckland',
 'Cape Town',
 'London',
 'Pallekele',
 'Barbados',
 'Sydney',
 'Melbourne',
 'Durban',
 'St Lucia',
 'Wellington',
 'Lauderhill',
 'Hamilton',
 'Centurion',
 'Manchester',
 'Abu Dhabi',
 'Mumbai',
 'Nottingham',
 'Southampton',
 'Mount Maunganui',
 'Chittagong',
 'Kolkata',
 'Lahore',
 'Delhi',
 'Nagpur',
 'Cardiff',
 'Chandigarh',
 'Adelaide',
 'Bangalore',
 'St Kitts',
 'Christchurch',
 'Trinidad']

In [11]:
df.head(2)

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,1,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground
1,1,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground

In [50]:
df['city'].unique()

array(['Melbourne', 'Adelaide', 'Mount Maunganui', 'Auckland',
       'Southampton', 'Cardiff', 'Nagpur', 'Bangalore', 'Lauderhill',
       'Dubai', 'Abu Dhabi', 'Sydney', 'Wellington', 'Hamilton',
       'Barbados', 'Trinidad', 'Colombo', 'St Kitts', 'Manchester',
       'Delhi', 'Lahore', 'Johannesburg', 'Centurion', 'Cape Town',
       'Mumbai', 'Kolkata', 'Durban', 'Chandigarh', 'Christchurch',
       'London', 'Nottingham', 'St Lucia', 'Pallekele', 'Mirpur',
       'Chittagong'], dtype=object)

# Current Score

In [12]:
print(df['runs'].dtype)

int64

In [13]:
df['current_score']= df.groupby('match_id')['runs'].cumsum()

In [14]:
df.head(5)

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current_score
0,1,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,0
1,1,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,0
2,1,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,1
3,1,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,3
4,1,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,3

In [15]:
# wicket left , balls left

# Balls left

In [16]:
df[["over","balls"]]=df['ball'].astype(str).str.split('.').apply(pd.Series)

In [17]:
df.tail()

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current_score,over,balls
116542,963,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,125,19,3
116543,963,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,125,19,4
116544,963,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium,125,19,5
116545,963,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,127,19,6
116546,963,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,128,19,7

In [18]:
df['ball_bowledd'] = (df['over'].astype('int')*6 ) + (df['balls'].astype('int'))

In [20]:
# df = df.drop(columns='ball_bowled' , axis = 1)

In [21]:
df.head(126)

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current_score,over,balls,ball_bowledd
0,1,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,0,0,1,1
1,1,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,0,0,2,2
2,1,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,1,0,3,3
3,1,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,3,0,4,4
4,1,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,3,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...
121,1,Australia,Sri Lanka,19.4,1,0,Melbourne,Melbourne Cricket Ground,161,19,4,118
122,1,Australia,Sri Lanka,19.5,1,TD Paine,Melbourne,Melbourne Cricket Ground,162,19,5,119
123,1,Australia,Sri Lanka,19.6,2,0,Melbourne,Melbourne Cricket Ground,164,19,6,120
124,1,Australia,Sri Lanka,19.7,4,0,Melbourne,Melbourne Cricket Ground,168,19,7,121
248,3,Australia,Sri Lanka,0.1,0,0,Adelaide,Adelaide Oval,0,0,1,1

In [22]:
print(df['ball_bowledd'].dtype)

int64

In [23]:
df['ball_left'] = 120 - df['ball_bowledd']
df['ball_left'] = df['ball_left'].apply(lambda x: 0 if x<0 else x)

In [24]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current_score,over,balls,ball_bowledd,ball_left
0,1,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,0,0,1,1,119
1,1,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,0,0,2,2,118
2,1,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,1,0,3,3,117
3,1,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,3,0,4,4,116
4,1,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,3,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...
116542,963,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,125,19,3,117,3
116543,963,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,125,19,4,118,2
116544,963,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium,125,19,5,119,1
116545,963,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,127,19,6,120,0
116546,963,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,128,19,7,121,0

# Wickets Left

In [25]:
df['player_dismissed'] = df['player_dismissed'].apply(lambda x: 0 if x==0 else 1)
df['player_dismissed'] = df['player_dismissed'].astype('int')
df['wickets_left'] = 10 - df['player_dismissed']

In [26]:
print(df['player_dismissed'].dtype)

int64

In [27]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current_score,over,balls,ball_bowledd,ball_left,wickets_left
0,1,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,0,0,1,1,119,10
1,1,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,0,0,2,2,118,10
2,1,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,1,0,3,3,117,10
3,1,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,3,0,4,4,116,10
4,1,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,3,0,5,5,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116542,963,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,125,19,3,117,3,10
116543,963,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,125,19,4,118,2,10
116544,963,Sri Lanka,Australia,19.5,0,1,Colombo,R Premadasa Stadium,125,19,5,119,1,9
116545,963,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,127,19,6,120,0,10
116546,963,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,128,19,7,121,0,10

# Current runrate

In [28]:
df['crr'] = (df['current_score'] * 6)/df['ball_bowledd']

In [29]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current_score,over,balls,ball_bowledd,ball_left,wickets_left,crr
0,1,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,0,0,1,1,119,10,0.000000
1,1,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,0,0,2,2,118,10,0.000000
2,1,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,1,0,3,3,117,10,2.000000
3,1,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,3,0,4,4,116,10,4.500000
4,1,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,3,0,5,5,115,10,3.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116542,963,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,125,19,3,117,3,10,6.410256
116543,963,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,125,19,4,118,2,10,6.355932
116544,963,Sri Lanka,Australia,19.5,0,1,Colombo,R Premadasa Stadium,125,19,5,119,1,9,6.302521
116545,963,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,127,19,6,120,0,10,6.350000
116546,963,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,128,19,7,121,0,10,6.347107

In [30]:
groups = df.groupby('match_id')
match_id = df['match_id'].unique()
last_five = []
for id in match_id:
    match_df = groups.get_group(id)
    last_five.extend(
        match_df['runs'].rolling(window=30).sum().values.tolist()
    )

In [32]:
df['last_five'] = last_five

# Calculating Total Score

In [36]:
final_df = df.groupby('match_id').sum()['runs'].reset_index().merge(df , on = 'match_id')

In [37]:
final_df

,match_id,runs_x,batting_team,bowling_team,ball,runs_y,player_dismissed,city,venue,current_score,over,balls,ball_bowledd,ball_left,wickets_left,crr,last_five
0,1,168,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,0,0,1,1,119,10,0.000000,NaN
1,1,168,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,0,0,2,2,118,10,0.000000,NaN
2,1,168,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,1,0,3,3,117,10,2.000000,NaN
3,1,168,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,3,0,4,4,116,10,4.500000,NaN
4,1,168,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,3,0,5,5,115,10,3.600000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51104,963,128,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,125,19,3,117,3,10,6.410256,32.0
51105,963,128,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,125,19,4,118,2,10,6.355932,32.0
51106,963,128,Sri Lanka,Australia,19.5,0,1,Colombo,R Premadasa Stadium,125,19,5,119,1,9,6.302521,32.0
51107,963,128,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,127,19,6,120,0,10,6.350000,33.0
51108,963,128,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,128,19,7,121,0,10,6.347107,32.0

In [40]:
final_df = final_df[['batting_team','bowling_team','city','current_score','ball_left','wickets_left','crr','last_five','runs_x']]

In [41]:
final_df

,batting_team,bowling_team,city,current_score,ball_left,wickets_left,crr,last_five,runs_x
0,Australia,Sri Lanka,Melbourne,0,119,10,0.000000,NaN,168
1,Australia,Sri Lanka,Melbourne,0,118,10,0.000000,NaN,168
2,Australia,Sri Lanka,Melbourne,1,117,10,2.000000,NaN,168
3,Australia,Sri Lanka,Melbourne,3,116,10,4.500000,NaN,168
4,Australia,Sri Lanka,Melbourne,3,115,10,3.600000,NaN,168
...,...,...,...,...,...,...,...,...,...
51104,Sri Lanka,Australia,Colombo,125,3,10,6.410256,32.0,128
51105,Sri Lanka,Australia,Colombo,125,2,10,6.355932,32.0,128
51106,Sri Lanka,Australia,Colombo,125,1,9,6.302521,32.0,128
51107,Sri Lanka,Australia,Colombo,127,0,10,6.350000,33.0,128
51108,Sri Lanka,Australia,Colombo,128,0,10,6.347107,32.0,128

In [42]:
final_df.isnull().sum()

batting_team         0
bowling_team         0
city                 0
current_score        0
ball_left            0
wickets_left         0
crr                  0
last_five        12169
runs_x               0
dtype: int64

In [43]:
final_df.dropna(inplace = True)

C:\Users\Manadip\AppData\Local\Temp\ipykernel_18996\1587496580.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.dropna(inplace = True)

In [45]:
final_df.isnull().sum()

batting_team     0
bowling_team     0
city             0
current_score    0
ball_left        0
wickets_left     0
crr              0
last_five        0
runs_x           0
dtype: int64

In [46]:
final_df = final_df.sample(final_df.shape[0])

In [47]:
final_df

,batting_team,bowling_team,city,current_score,ball_left,wickets_left,crr,last_five,runs_x
3691,Sri Lanka,India,Colombo,169,1,10,8.521008,49.0,170
22280,Sri Lanka,Pakistan,London,37,81,10,5.692308,35.0,138
5395,Sri Lanka,India,Mumbai,45,78,10,6.428571,36.0,135
40496,Sri Lanka,England,Chittagong,94,45,10,7.520000,37.0,189
10715,India,West Indies,Mumbai,116,59,10,11.409836,48.0,240
...,...,...,...,...,...,...,...,...,...
14390,England,Australia,Southampton,117,32,10,7.977273,27.0,179
32591,Bangladesh,Pakistan,Pallekele,175,0,9,8.750000,42.0,175
21082,Sri Lanka,Pakistan,London,87,59,10,8.557377,27.0,150
5212,India,South Africa,Centurion,157,13,10,8.803738,51.0,188
2292,England,New Zealand,Hamilton,60,72,10,7.500000,36.0,194

In [48]:
import pickle
pickle.dump(final_df, open('final_data_frModel.pkl','wb'))